### ISSUE TITLE
Create a Wheel of Fortune Game in Js

### ISSUE THREAD

**Issue by Aanchi-glitch2744** [Aanchi-glitch2744/JavaScriptGames-Hacktoberfest2023#21]

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign me this issue.

**Comment by Aanchi-glitch2744** [comment]
Assigned to you. Make it colorful

**Comment by anushkp1107** [comment]
@Aanchi-glitch2744 I wish to contribute under hactoberfest 2023. Kindly assign this to me.

**Comment by Aanchi-glitch2744** [comment]
@anushkp1107 Assigned to you
