### ISSUE TITLE
This project got excluded from HacktoberFest 2023

### ISSUE THREAD

**Issue by akash-rajak** [Aanchi-glitch2744/JavaScriptGames-Hacktoberfest2023#46]

**Comment by Aanchi-glitch2744** [comment]
How can you say that?

**Comment by akash-rajak** [comment]
![image](https://github.com/Aanchi-glitch2744/JavaScriptGames-Hacktoberfest2023/assets/57003737/8036247c-4c77-43f8-aba6-5033bf809ce9)

**Comment by Aanchi-glitch2744** [comment]
This is bcuz I rejected your code dear.
