### ISSUE TITLE
Create a Tic Tac Toe Game

### ISSUE THREAD

**Issue by Aanchi-glitch2744** [Aanchi-glitch2744/JavaScriptGames-Hacktoberfest2023#8]

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign me this.

**Comment by anushkp1107** [comment]
@Aanchi-glitch2744 I would like to work on tic tac toe game using javascript under hacktoberfest 2023. Kindly assign this to me.

**Comment by GautamThorani** [comment]
@Aanchi-glitch2744 let me work on this. Assign it to me
